### ISSUE TITLE
doesn't pass bool false through

### ISSUE THREAD

**Issue by austinhallock** [claydotio/portal-gun#3]
Due to https://github.com/claydotio/portal-gun/blob/master/src/index.coffee#L157 `false` doesn't get passed from parent to child. 

Unsure of why the or is there, so not going to change myself. Adding a question mark (check if defined instead of truthiness) to the result part probably fixes it

**Comment by Zolmeister** [comment]
https://github.com/claydotio/portal-gun/commit/256823be76fa525aff5cf35ec1d9b6c1cf20af0b

**Comment by Zolmeister** [comment]
v0.2.6
